import { ChecklistTemplate } from "@/types/checklist";

export const safetyHealthChecklist: ChecklistTemplate = {
  key: "safetyHealth",
  title: "Health & Safety Checklist",
  sections: [
    {
      id: "A",
      title: "HEALTH & WELFARE FACILITIES",
      criticality: "non-life-critical",
      questions: [
        { id: "A1", text: "Have adequate supplies of potable drinking water been provided within reasonable distance from work location?", defaultPossible: "2" },
        { id: "A2", text: "Are shaded rest areas available, within reasonable distance from the work location, complete with tables and chairs and constructed in such a way to reduce the temperature inside the shelter less than the outside working area?", defaultPossible: "2" },
        { id: "A3", text: "Is food that is to be eaten by others stored in hygienic conditions?", defaultPossible: "2" },
        { id: "A4", text: "Are washing and sanitary facilities cleaned regularly and maintained to a good standard?", defaultPossible: "2" },
        { id: "A5", text: "Are there means of providing hot, cold (or warm) running water and the provision of soap and towels or other suitable means of drying?", defaultPossible: "2" },
        { id: "A6", text: "Are measures taken to control smoking in designated areas only?", defaultPossible: "2" },
        { id: "A7", text: "Do employees have access to clean cups/bottles that prevents need for sharing or drinking directly from water discharge point?", defaultPossible: "2" },
        { id: "A8", text: "Igloo boxes/cool mans/water containers sealed, clean, labelled, used only for drinking, are not exposed to the direct sun light?", defaultPossible: "2" },
        { id: "A9", text: "Are the areas next to the drinking water distribution points clean and free of food waste?", defaultPossible: "2" },
        { id: "A10", text: "Is the cartridge of all water coolers changed on regular basis? Is the potable water controlled on regular basis?", defaultPossible: "2" },
        { id: "A11", text: "Proper ventilation is provided at the resting areas or at the working places?", defaultPossible: "2" },
        { id: "A12", text: "Are all food wastes disposed of in closed containers and regularly removed from site?", defaultPossible: "2" },
        { id: "A13", text: "Are eating/dining areas kept clean and orderly?", defaultPossible: "2" },
        { id: "A14", text: "Toilets facilities are sufficient (1 toilet/20 workers), clean and in good condition (with exhaust fan)?", defaultPossible: "2" },
        { id: "A15", text: "Have all workers been made aware of the first-aid provisions, including how to identify and summon first aiders in an emergency?", defaultPossible: "2" },
        { id: "A16", text: "Are adequate first aid kits available, stocked, clearly identifiable and easily accessible? A first aid box is required for each 25 employees and clinic above 500 employees.", defaultPossible: "2" },
        { id: "A17", text: "If employees are working alone, can they summon help in the event of a medical emergency?", defaultPossible: "2" },
        { id: "A18", text: "Are the required number of trained and certified first aiders on-site and easily identified in the event of an emergency?", defaultPossible: "2" },
      ],
    },
    {
      id: "B",
      title: "LADDERS",
      criticality: "non-life-critical",
      questions: [
        { id: "B1", text: "Do side rails of all ladders extend approximately 1 meter above landings? When this is not practical, are grab rails installed?", defaultPossible: "2" },
        { id: "B2", text: "Are all ladders in use tied, blocked, or otherwise secured to prevent displacement?", defaultPossible: "2" },
        { id: "B3", text: "Are non-metallic approved ladders used during operations where employees may come into contact with electrical circuits or systems?", defaultPossible: "2" },
        { id: "B4", text: "Are ladders in good condition, free from defects, with proper footings, rungs, side rails and warning labels?", defaultPossible: "2" },
        { id: "B5", text: "Are ladders weekly inspected and certified by competent person and attached inspection tag (similar to scaffold tags) that includes the inspection date, color code for the month, area serial number, supervisor and inspector's name/signature?", defaultPossible: "2" },
        { id: "B6", text: "Does the ladder display the current applicable quarter color code?", defaultPossible: "2" },
        { id: "B7", text: "Are ladders set at the correct angle (pitch) of 75°?", defaultPossible: "2" },
        { id: "B8", text: "Are straight ladders without landing platforms no longer than 20 feet long (6m)?", defaultPossible: "2" },
      ],
    },
    {
      id: "C",
      title: "SCAFFOLDING",
      criticality: "life-critical",
      questions: [
        { id: "C1", text: "Is the scaffold being erected under the direction of a competent person? Is the scaffold inspection tag displayed, signed and in date?", defaultPossible: "2" },
        { id: "C2", text: "Is the access to the scaffold safe, tied off and in good condition i.e. at top; free from defects; extend 1 meter past step off point; unobstructed access to platform?", defaultPossible: "2" },
        { id: "C3", text: "Is the scaffold secured and stable i.e. to building or adequately braced and erected, inspected by competent person before use?", defaultPossible: "2" },
        { id: "C4", text: "Is the scaffold plumb, square, level and built on level ground using standard base plates and sole boards?", defaultPossible: "2" },
        { id: "C5", text: "Is adequate, safe access provided to all working areas i.e. boarded walkways on scaffold access over potential hazards?", defaultPossible: "2" },
        { id: "C6", text: "Does scaffolding have adequate top rail (approx. 1m in height); adequate midtrial (approx. 50cm in height); have adequate toe boards and is it free from visible defect?", defaultPossible: "2" },
        { id: "C7", text: "Are all special types of scaffolds (Hanging, Cantilever, etc.) and those higher than 38 meters has designed by a register professional engineer?", defaultPossible: "2" },
        { id: "C8", text: "Is the scaffold supported with a height to base width ratio of more than four to one (4:1) be restrained from tipping by guying, tying, bracing or other equivalent means?", defaultPossible: "2" },
        { id: "C9", text: "Are all scaffolds provided with an access ladder that extends at least 91 cm above the platform? Are gates being used as guard rail system?", defaultPossible: "2" },
        { id: "C10", text: "Is the wooden scaffold planking with a size minimum of nominal 2\" X 10\" and certified and stamped as scaffold grade lumber?", defaultPossible: "2" },
        { id: "C11", text: "Is the mobile scaffold completely braced by cross, horizontal, or diagonal braces and the vertical member secured laterally?", defaultPossible: "2" },
        { id: "C12", text: "Is the mobile scaffold casters and wheels are locked while the scaffold is in used in a stationary manner?", defaultPossible: "2" },
        { id: "C13", text: "Is the height of the mobile scaffold top platform meet the 3 times the minimum base dimension? If the height is greater than the required minimum, is the out rigger provided?", defaultPossible: "2" },
        { id: "C14", text: "Is the safe means of access to mobile scaffold work platform provided?", defaultPossible: "2" },
      ],
    },
    {
      id: "D",
      title: "Personal Protective Equipment",
      criticality: "non-life-critical",
      questions: [
        { id: "D1", text: "Is suitable head, eye, foot and hand protection being worn correctly by all workers and is it in good condition within its shelf life and free from visible defect? Enforcement system in place?", defaultPossible: "2" },
        { id: "D2", text: "Are all workers wearing high visibility vests/tops and is it in good condition and free from visible defect?", defaultPossible: "2" },
        { id: "D3", text: "Are all workers wearing ear protection (ear muffs of inserts) correctly based upon the protection factor in high noise area? Hearing protection supplied reduce the level of noise or legally permissible level? Have Hearing Protection Zones been established?", defaultPossible: "2" },
        { id: "D4", text: "Are all workers wearing PPE protection based on identified protection factor (dust masks, respirators) correctly in areas where respiratory hazards exist and properly face fitted? (i.e. dusty environments; fumes; chemicals);", defaultPossible: "2" },
        { id: "D5", text: "Are all workers wearing hand protection (e.g. safety gloves) where appropriate? i.e. handling chemicals; concreting; steel fixing; sand bedding", defaultPossible: "2" },
        { id: "D6", text: "Is PPE properly maintained and stored when not in use?", defaultPossible: "2" },
      ],
    },
    {
      id: "E",
      title: "ELECTRICAL",
      criticality: "life-critical",
      questions: [
        { id: "E1", text: "Does the site have an up-to-date Electrical Plan (single-line diagram) that reflects the safe installation of all electrical facilities in accordance with the HSE procedures?", defaultPossible: "2" },
        { id: "E2", text: "Has power supply equipment (i.e. generators) been properly earthed? i.e. copper rod placed 1.5m into the ground?", defaultPossible: "2" },
        { id: "E3", text: "Are all electrical cords, cables and devices suitable for use and in general good condition with no visible defects, covered to prevent exposure to moving/electrical components and situated in a safe location so not as to create a trip or electrocution hazard?", defaultPossible: "2" },
        { id: "E4", text: "Do all electrical distribution boards have GFCI's (Ground Fault Circuit Interrupters) or residual current devices fitted, circuit breaker labels, dead front panels or covers, free of unused openings, locked to prevent unauthorized entry, point of contact for authorized entry?", defaultPossible: "2" },
        { id: "E5", text: "Are all GFCI inspected and checked quarterly? Are there records of the checks?", defaultPossible: "2" },
        { id: "E6", text: "Do all power supplies have the correct loading (i.e. there is not more than one cable running into one plug)", defaultPossible: "2" },
        { id: "E7", text: "Where cables have been extended, have the correct fittings been utilized and has the connection been made safe (prohibit splicing of cables)", defaultPossible: "2" },
        { id: "E8", text: "Is all unserviceable electrical equipment quarantined until repaired or safely disposed?", defaultPossible: "2" },
      ],
    },
    {
      id: "F",
      title: "HOUSEKEEPING",
      criticality: "non-life-critical",
      questions: [
        { id: "F1", text: "Is the site free of litter and unwanted materials?", defaultPossible: "2" },
        { id: "F2", text: "Are scaffolds, walkways, work areas and platforms free of loose materials?", defaultPossible: "2" },
        { id: "F3", text: "Are all nails removed from wood prior to being stacked/stored for re-use or removal from site?", defaultPossible: "2" },
        { id: "F4", text: "Are all materials stored neatly, on level ground and to a safe height?", defaultPossible: "2" },
        { id: "F5", text: "Is there sufficient bins and waste containers in the work site? Are bins only loaded to the top and not overflowing?", defaultPossible: "2" },
      ],
    },
    {
      id: "G",
      title: "COMPRESSED GAS",
      criticality: "non-life-critical",
      questions: [
        { id: "G1", text: "Are compressed gas cylinders secured, used, stored and transported in an upright position at all times?", defaultPossible: "2" },
        { id: "G2", text: "Is cylinder(s) capped at all times, except when a cylinder is in service?", defaultPossible: "2" },
        { id: "G3", text: "Are compressed gas cylinders stored/located away from sources of ignition to avoid exposure to sparks, hot slag, or flames, or, if these can not be avoided, are fire-resistant shields provided?", defaultPossible: "2" },
        { id: "G4", text: "Are welding gases stored in well ventilated, isolated areas and segregated by type of gas (e.g. oxygen, acetylene)? Are gas cylinders labelled detailing their contents?", defaultPossible: "2" },
        { id: "G5", text: "Are cylinders stored in well-protected, ventilated, dry locations, at least 20 feet (6.1 meters) (unless protected by a wall at least 5 feet/1.5 meters high having a fire-resistance rating of at least one hour) from highly combustible materials and combustible gas cylinders, and away from egress routes such as stairways and elevators?", defaultPossible: "2" },
        { id: "G6", text: "Are gas cylinders protected against exposure to high temperature extremes and/or shock?", defaultPossible: "2" },
      ],
    },
    {
      id: "H",
      title: "WORKING IN CONFINED SPACES",
      criticality: "life-critical",
      questions: [
        { id: "H1", text: "Has all confined spaces been identified as such and an entry permit issued, valid and posted at the entrance?", defaultPossible: "2" },
        { id: "H2", text: "Are all personnel about to enter or inside confined space authorized and trained to do so and are fit for work?", defaultPossible: "2" },
        { id: "H3", text: "Is the confined space adequately barricaded and signed to warn of the hazards? i.e. \"Confined Space DANGER - No entry to unauthorized personnel\"", defaultPossible: "2" },
        { id: "H4", text: "Has a system been introduced to control access/egress within the confined space and an attendant in place to supervise this process? Particularly emergency egress?", defaultPossible: "2" },
        { id: "H5", text: "Is suitable access installed, where practical, to and from the confined space?", defaultPossible: "2" },
        { id: "H6", text: "Where identified on the permit, has gas detection been completed within the confined space both prior to entry and during the work? Is the equipment to be used calibrated with third party, in date and in good working order?", defaultPossible: "2" },
        { id: "H7", text: "Have all employees been trained on the procedure, use of equipment and briefed each day on the confined space hazards and risks by a competent person?", defaultPossible: "2" },
        { id: "H8", text: "Have adequate emergency provisions been installed to rescue personnel as per rescue plan along with trained, competent rescue team for the confined space? Do they carry out practice rescues?", defaultPossible: "2" },
        { id: "H9", text: "Adequate natural or forced ventilation provided for confined space?", defaultPossible: "2" },
        { id: "H10", text: "All necessary equipment used in a confined space is designed for the working environment (i.e. explosion proof lighting)?", defaultPossible: "2" },
      ],
    },
    {
      id: "I",
      title: "LIFTING OPERATIONS",
      criticality: "life-critical",
      questions: [
        { id: "I1", text: "Has a competent person been appointed to plan, and supervise each lift?", defaultPossible: "2" },
        { id: "I2", text: "Are Saudi license/third party certificate for operators and certificate of training for crane operator and riggers available?", defaultPossible: "2" },
        { id: "I3", text: "Are there up-to-date thorough examination and test certificates available for all lifting equipment and accessories?", defaultPossible: "2" },
        { id: "I4", text: "Is the crane equipped with operating manual, load chart, fire extinguisher?", defaultPossible: "2" },
        { id: "I5", text: "All safety devices and operational aids are on the crane and in proper working order?", defaultPossible: "2" },
        { id: "I6", text: "Cords and lacings (lattice boom cranes only) not damaged, bent or with cracked welds?", defaultPossible: "2" },
        { id: "I7", text: "Are all running ropes, counterweight ropes and trolley ropes inspected and in good working condition? Wedge sockets proper installed?", defaultPossible: "2" },
        { id: "I8", text: "Crane properly setup: outriggers fully extended, tires off ground, load swing, counterweight, radius, boom length?", defaultPossible: "2" },
        { id: "I9", text: "Were ground conditions verified for proper equipment support?", defaultPossible: "2" },
        { id: "I10", text: "Has a lift plan been developed? Is the lift plan for the operation that has been briefed to everyone involved in the lift?", defaultPossible: "2" },
        { id: "I11", text: "Is the weight of each load and its center of gravity known (by operator and riggers/slinger) prior to the lift commencing?", defaultPossible: "2" },
        { id: "I12", text: "Has the crane operator completed daily/weekly inspection of crane?", defaultPossible: "2" },
        { id: "I13", text: "Where excavators are used as lifting devices, is the safe working load (SWL) displayed and a lifting point installed on the equipment?", defaultPossible: "2" },
        { id: "I14", text: "Verify (if crane is in operation) to determine safe work practices (e.g. proper rigging techniques, crane setup, demarcation, worker behavior during lifting operations, operator skills)", defaultPossible: "2" },
        { id: "I15", text: "Has a rescue plan (e.g. tower cranes) been devised and practiced, to recover anyone stranded at height?", defaultPossible: "2" },
        { id: "I16", text: "Have over-sailing rights of adjacent properties or public areas been obtained where necessary?", defaultPossible: "2" },
      ],
    },
    {
      id: "J",
      title: "LIFTING ACCESSORIES",
      criticality: "life-critical",
      questions: [
        { id: "J1", text: "Is 3rd party certificate and training available for lifting gear?", defaultPossible: "2" },
        { id: "J2", text: "Are all lifting accessories correctly color coded according to applicable quarter i.e. ORANGE- 1st Quarter; GREEN- 2nd Quarter; BLUE- 3rd Quarter; YELLOW- 4th Quarter", defaultPossible: "2" },
        { id: "J3", text: "Are all lifting accessories in good condition and free from defect?", defaultPossible: "2" },
        { id: "J4", text: "Is chaffing gear used to protect slings (e.g. synthetic slings) and equipment from damage due to sharp corners and edges?", defaultPossible: "2" },
        { id: "J5", text: "Is the rigging gear used in accordance with its working load limit?", defaultPossible: "2" },
        { id: "J6", text: "Do all lifting accessories have a SWL (safe working load) displayed and identification number?", defaultPossible: "2" },
        { id: "J7", text: "Do all lifting hooks have a safety catch i.e. spring loaded to prevent slings from slipping from hook, installed and a working condition?", defaultPossible: "2" },
        { id: "J8", text: "Are Damaged lifting devices removed from the workplace?", defaultPossible: "2" },
      ],
    },
    {
      id: "K",
      title: "WORKSITE SECURITY",
      criticality: "non-life-critical",
      questions: [
        { id: "K1", text: "Is there a current security plan in place that addresses policies for access control and emergency response?", defaultPossible: "2" },
        { id: "K2", text: "Does the access control policy address visitor registration, ID badge usage, escorting and other requirements for all visitors and contractors?", defaultPossible: "2" },
        { id: "K3", text: "Is there a system for centralized reporting and analysis of all security related incidents and suspicious activities?", defaultPossible: "2" },
        { id: "K4", text: "Is appropriate perimeter protection in place? Are the perimeter gates secured and in good working condition and not accessible to public?", defaultPossible: "2" },
        { id: "K5", text: "Is there regular patrolling of the perimeter to inspect the fence line damage, clear zone, obstructions, unoccupied/unidentified vehicles and other breaches?", defaultPossible: "2" },
        { id: "K6", text: "Is the access approaching, and entry into, the worksite controlled? Are all visitors and contractors screened and required to sign-in/sign-out and produce valid photo identification?", defaultPossible: "2" },
        { id: "K7", text: "Are the visitors and contractors briefed on the site's safety and security procedures including evacuation & restricted areas?", defaultPossible: "2" },
      ],
    },
    {
      id: "L",
      title: "FALL PREVENTION & PROTECTION",
      criticality: "life-critical",
      questions: [
        { id: "L1", text: "Is fall protection provided for activities that require employees to work at heights 6 ft. (1.83m) or above engage in leading edge work?", defaultPossible: "2" },
        { id: "L2", text: "Are guardrail systems or machine guarding provided for workers above Dangerous Equipment?", defaultPossible: "2" },
        { id: "L3", text: "Are the correct fall protection systems used (e.g. PFAS; guardrails; safety nets; Horizontal Life Lines, retractable life line, Controlled Access Zones) in line with work being performed (e.g. use of hierarchy of controls)?", defaultPossible: "2" },
        { id: "L4", text: "Is adequate access provided to areas where work at height is to be performed (e.g. ladder access; walkways strong enough to support workers and free from obstruction)?", defaultPossible: "2" },
        { id: "L5", text: "Is the use of safety belts restricted to positioning only?", defaultPossible: "2" },
        { id: "L6", text: "Are fall protection systems and devices (e.g. PFAS; safety nets; lifelines; Retractable life line) inspected to ensure in good condition and free from defect?", defaultPossible: "2" },
        { id: "L7", text: "Are all employees using harnesses tied off to a anchorage point that is, as a minimum, at working at height level or above and will support a minimum of 5000lbs?", defaultPossible: "2" },
        { id: "L8", text: "Are safety net systems as close as practicable, but no more than 30ft (10m) below?", defaultPossible: "2" },
        { id: "L9", text: "Are safety net systems third party drop test certified and have an ID Tag, name of mfg., type of material, date of mfg., size of net and serial #?", defaultPossible: "2" },
        { id: "L10", text: "Do employees on aerial lifts stand firmly on the floor of the basket or platform (climbing on the railing or using planks, ladders, or other devices is prohibited) and they wearing a harness that is securely tied off?", defaultPossible: "2" },
        { id: "L11", text: "Are floor opening covers capable of supporting the maximum potential load to which they may be subjected, completely cover the opening hole and extend a minimum of 4 inches (10.2cm) from the edges and marked \"FLOOR OPENING-DANGER, DO NOT REMOVE\"?", defaultPossible: "2" },
        { id: "L12", text: "Are guardrails complete and securely installed such that they are capable of withstanding a 200lb (90.7kg) force from any direction without failing?", defaultPossible: "2" },
        { id: "L13", text: "Are life line systems flagged 6ft (2m) apart and flagged 34\"-39\" (13.5-15.5 cm) in height, made of wire rope, have a tensile strength of 500lbs (227kg), and 16lb (7kg) tipping force?", defaultPossible: "2" },
        { id: "L14", text: "Does contractor take adequate steps to ensure protection from falling objects (e.g. toe-boards, netting, canopies, barricades, no materials stored on edge)?", defaultPossible: "2" },
      ],
    },
    {
      id: "M",
      title: "MACHINES & EQUIPMENT",
      criticality: "life-critical",
      questions: [
        { id: "M1", text: "Has the operator of the machine/equipment been trained in its use and hold relevant competence certification (e.g., electrical, mechanical, or Saudi license where applicable)? Are qualifications of operators available for review?", defaultPossible: "2" },
        { id: "M2", text: "Does the machine/equipment have adequate warning systems installed (e.g., audible alarms, indicator lights, emergency stop buttons)?", defaultPossible: "2" },
        { id: "M3", text: "Is the machine/equipment in good working condition and free from visible defects?", defaultPossible: "2" },
        { id: "M4", text: "Is the machine/equipment being used for its intended purpose and within its design limits (e.g., load, capacity, electrical rating)?", defaultPossible: "2" },
        { id: "M5", text: "Is the area around the machine/equipment controlled and free from hazards (e.g., adequate clearance, proper signage, restricted access)?", defaultPossible: "2" },
        { id: "M6", text: "Where applicable, is a competent person supervising machine/equipment operation and ensuring safe operation practices?", defaultPossible: "2" },
        { id: "M7", text: "Are safety devices installed (e.g., guards, interlocks) in place, functional, and used correctly?", defaultPossible: "2" },
        { id: "M8", text: "Are daily or periodic inspections conducted, and are records readily available for review?", defaultPossible: "2" },
        { id: "M9", text: "Are any alterations or repairs to the machine/equipment approved in writing by the manufacturer or competent authority?", defaultPossible: "2" },
        { id: "M10", text: "Where relevant (e.g., lifting or mobile equipment), are safe operational procedures followed, such as stable positioning, securing loads, and preventing tipping hazards?", defaultPossible: "2" },
      ],
    },
    {
      id: "N",
      title: "VEHICLE (TRAFFIC) MANAGEMENT",
      criticality: "life-critical",
      questions: [
        { id: "N1", text: "Have traffic routes around the work area been demarcated with signage?", defaultPossible: "2" },
        { id: "N2", text: "Have pedestrian routes around the route been sufficiently marked and sign posted?", defaultPossible: "2" },
        { id: "N3", text: "Does contractor ensure pedestrian/vehicle interface is kept to a minimum?", defaultPossible: "2" },
        { id: "N4", text: "In areas where personnel are working close to machinery/equipment, are banksman employed to control/direct movement?", defaultPossible: "2" },
        { id: "N5", text: "Are adequate turning circles allocated for vehicles having to enter/exit work area?", defaultPossible: "2" },
        { id: "N6", text: "Is the need for reversing minimized as much as possible through the use of one-way systems and turning points?", defaultPossible: "2" },
        { id: "N7", text: "Are traffic routes kept as far as possible away from work areas (e.g. fuel storage, welfare areas) with particular regard for excavations and lifting operations?", defaultPossible: "2" },
        { id: "N8", text: "Are traffic routes well maintained and ground conditions suitable for equipment to travel over?", defaultPossible: "2" },
        { id: "N9", text: "Are car parking areas well defined and access from car to offices/work areas defined and designated to minimize pedestrian/vehicle interface?", defaultPossible: "2" },
        { id: "N10", text: "Is adequate lighting provided for vehicles (e.g. nightshift operations)?", defaultPossible: "2" },
        { id: "N11", text: "Are junctions adequately sign posted and protected to ensure all drivers are aware of the impending hazard?", defaultPossible: "2" },
      ],
    },
    {
      id: "O",
      title: "HOT WORKS",
      criticality: "life-critical",
      questions: [
        { id: "O1", text: "Is a hot work permit in place covering the work activity and is it valid, in date?", defaultPossible: "2" },
        { id: "O2", text: "Is the area cleared of any combustible materials prior to hot works commencing?", defaultPossible: "2" },
        { id: "O3", text: "Is a fire extinguisher located nearby and is it of a suitable type, in good condition and maintained?", defaultPossible: "2" },
        { id: "O4", text: "Is area screened off with fire retardant material to protect bystanders?", defaultPossible: "1" },
        { id: "O5", text: "Is a fire watch in attendance at the location both during and after hot works activities?", defaultPossible: "2" },
        { id: "O6", text: "Is the area signposted and controlled to protect other work areas nearby, where appropriate?", defaultPossible: "2" },
        { id: "O7", text: "Do hoses have flashback arrestors installed at both torch and bottled ends? Are hoses and torches in good condition and free from visible defect?", defaultPossible: "2" },
        { id: "O8", text: "Is the area well ventilated (e.g. dilution, local exhaust) to minimize inhalation of fumes?", defaultPossible: "2" },
      ],
    },
    {
      id: "P",
      title: "BARRICADES AND FENCING",
      criticality: "non-life-critical",
      questions: [
        { id: "P1", text: "Are barriers installed where hazards exist to either contain the hazard or protect workers from coming into contact with hazards i.e. excavations; plant/pedestrian segregation?", defaultPossible: "2" },
        { id: "P2", text: "Are barriers visible to all in the work area with consideration for relevant night time activities i.e. red/white tape, amber flashing lights at night?", defaultPossible: "2" },
        { id: "P3", text: "Are barriers properly maintained, kept clean and in good condition?", defaultPossible: "2" },
        { id: "P4", text: "Are clear entrance and exit ways installed in and out of the barricaded areas?", defaultPossible: "2" },
        { id: "P5", text: "Are signs posted warning workers of the hazards existing within the barriers?", defaultPossible: "2" },
        { id: "P6", text: "Is the barricade area of sufficient size to afford adequate protection i.e. set far enough back from hazard?", defaultPossible: "2" },
        { id: "P7", text: "Are appropriate barriers (e.g. water-filled, concrete) installed properly and sufficient to control the hazard?", defaultPossible: "2" },
      ],
    },
    {
      id: "Q",
      title: "TOOLS & ACCESSORIES",
      criticality: "non-life-critical",
      questions: [
        { id: "Q1", text: "Are power and hand tools in good condition and free from any visible defects?", defaultPossible: "2" },
        { id: "Q2", text: "Are power and hand tools unaltered and suitable for the activity they are being used for?", defaultPossible: "2" },
        { id: "Q3", text: "Are powder actuated tools prohibited from use in explosive of flammable atmospheres?", defaultPossible: "2" },
        { id: "Q4", text: "Are defective tools removed from the site immediately and returned to the stores?", defaultPossible: "2" },
        { id: "Q5", text: "Do all hand tools have the appropriate guarding systems as installed by the manufacturer and have not been tampered with?", defaultPossible: "2" },
        { id: "Q6", text: "Are power tools and equipment's inspected, color coded, and recorded?", defaultPossible: "2" },
      ],
    },
    {
      id: "R",
      title: "MANAGEMENT COMMITMENT",
      questions: [
        { id: "R1", text: "Is the HSE Plan and is it available on site.", defaultPossible: "2" },
        { id: "R2", text: "Do subcontractor HSE Staff have a degree in Safety, NEBOSH, BCSP, or BCRSP in line with HSE Plan requirements? (List # HSE staff with trade background only qualifications considered comment)", defaultPossible: "2" },
        { id: "R3", text: "Are the Senior Managers and Emergency responders phone numbers displayed in case of emergency or enquiry by staff. Are the posters in the appropriate language?", defaultPossible: "2" },
        { id: "R4", text: "Is there HSE staff in a ratio of 1:50 for all subcontractors on day and night shift.", defaultPossible: "2" },
        { id: "R5", text: "Does the construction Manager and SPIC participate in HSE activities like planned inspections, assessments and investigation. (Spot check documents)", defaultPossible: "2" },
        { id: "R6", text: "Does the SPIC run the work brief Meetings before any work is commenced? Is there evidence to support this?", defaultPossible: "2" },
        { id: "R7", text: "Do the Site Based sub contractor Health and Safety Staff conduct site daily Inspection? Is there any evidence of this Inspection produced? Are all violations being managed and closed out?", defaultPossible: "2" },
        { id: "R8", text: "Does the site have documented records of hazards reported and records of closure?", defaultPossible: "2" },
        { id: "R9", text: "Are weekly tool box meeting held with all staff and documented accordingly?", defaultPossible: "2" },
        { id: "R10", text: "Do the SPIC and senior site staff attend the audits done by Consultant / Client and document closure of hazards identified?", defaultPossible: "2" },
      ],
    },
  ],
};
